<?php namespace Gorob4ik\Birds;

use System\Classes\PluginBase;
use Event;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Event::listen('eloquent.creating: SaurabhDhariwal\Comments\Models\Comments', function($game){
            return true;
        });
    }
}
