<?php namespace Gorob4ik\Birds;

use System\Classes\PluginBase;
use Queue;
use Event;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
        return [
            'Gorob4ik\Birds\Components\SomeBird'       => 'someBirds',
        ];
    }

    public function registerSettings()
    {
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Event::listen('eloquent.creating: SaurabhDhariwal\Comments\Models\Comments', function($game){
            return true;
        });


        Event::listen('backend.menu.extendItems', function($manager) {
            $manager->removeMainMenuItem('Rainlab.User', 'user');
        });

        Queue::push('TestCron', ['message' => 'test']);
    }
}
